---
title: "The future of corn and beans in the tidyverse"
author: "Ranae Dietzel and Andee Kaplan"
date: "October 28, 2016"
output: html_document
---

The "future" dataset was generated by running a cropping systems model (APSIM) with daily weather predictions generated by a climate model. It represents 65 years of a corn-soybean rotation in central Iowa, USA, from 1999 to 2064. You already have this dataset in your lab/week_09 folder.   

```{r, eval=FALSE}
library(tidyverse)
#may also need library(lubridate)

data_dictionary<-data.frame(variable = c("date", "rain", "soil_water", "soil_temp", "soy_yield", "maize_yield", "nh4", "no3", "n_fixation", "n_leaching", "soil_n_min", "n_uptake"), unit = c("dd/mm/yyyy", "mm", "mm", "degC", "kg/ha", "kg/ha", "kg/mg","kg/mg", "kg", "kg", "kg", "kg"),definition = c("date", "mm of rain", "amount of water in the soil to 15 cm", "soil temp at 15 cm", "soybean grain yield","maize grain yield", "ammonium concentration in soil","nitrate concentration in soil", "kg of nitrogen fixed", "kg of nitrogen leached","kg of soil nitrogen produced by mineralization", "kg of nitrogen taken up by the plant"))  

future<-read_csv("future.csv", na = "?") 
```

Please make the following figures from this dataset:    
1. Change in yearly average soil temperature over all years.  
2. Average cumulative rain for each month. X axis should only list 12 months.  
3. Change in yield over time, with one facet for corn and one for soybean.      
4. The relationship between soil water and NO3 with a line drawn through it (hint: `method='lm'`).  
5. An interesting graph of your choice!  

These figures do not need to be beautiful, but they do need to be professional.  Each should have a title, correctly labeled axes, and legend that does not depend on abbreviations.  



